---
spring:
  profiles:    default: local

logging:
  level:
    io.github.learnjaxrpc.config: DEBUG

---
spring:
  config:
    activate:    
      on-profile: local

---
spring:
  config:
    activate:    
      on-profile: unittest

