---
spring:
  profiles:
    default: local

logging:
  level:
    io.github.learnjaxrpc.config: DEBUG
    org.apache.axis.configuration: OFF

---
spring:
  config:
    activate:    
      on-profile: local

---
spring:
  config:
    activate:    
      on-profile: unittest

